# Generated by Django 2.1.5 on 2019-12-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
