# Generated by Django 2.1.5 on 2019-12-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHOPLINE_WEB', '0004_auto_20191129_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
